var course = [
    {
        "id": 1,
        "image": "https://i.ebayimg.com/00/s/NTc2WDEwMjQ=/z/YK8AAOSwWnpdG2X9/$_86.JPG",
        "title" : "Cisco CCNA 200-301 – The Complete Guide to Getting Certified",
        "instructor": "Bombel Angela",
        "price" : 9.99,
    },
    {
        "id": 2,
        "image": "https://progressbangladesh.com/en/wp-content/uploads/sites/6/2020/04/word-image-6.jpeg",
        "title" : "Photography Masterclass: A Complete Guide to Photography",
        "instructor": "Rahul Portel",
        "price" : 19.99,
    },
    {
        "id": 3,
        "image":"https://2.bp.blogspot.com/-rS1H8Wxnne8/XH_MCH4kDMI/AAAAAAAANZY/XKyzFcmerw8lqZ-IQJYVjOOytJD6tjcpgCLcBGAs/s400/The%2BWEb%2BDeveloper%2BBootcamp.png" ,
        "title" : "The Complete 2020 Web Development Bootcamp",
        "instructor": "Dr. Angela Yu",
        "price" : 10.99,
    },
    {
        "id": 4,
        "image": "https://www.idp.com/medias/Building-and-Architecture-370x278.jpg?context=bWFzdGVyfHJvb3R8MzAxMDF8aW1hZ2UvanBlZ3xoNGYvaDY1Lzk5MDgxNjc2MzkwNzAuanBnfGU2OTM4MDRmYWNiMjAzY2YzZjg3ODQ1OGI0NWY4ZjRhMDM5MWI5NGY0NDVjZmQ3MTM0NTAwNGJjMjRlZDI5N2U",
        "title" : "AWS Certified Solutions Architect Associate: SAA-C02 exam",
        "instructor": "David Bombel",
        "price" : 15.99,
    },
    {
        "id": 5,
        "image": "https://miro.medium.com/max/1800/1*5eV1xmJs2-sJ4DdejfdnQA.png",
        "title" : "The Complete Guide to Getting Certified-JavaSrcipt",
        "instructor": "Zaid Sabih",
        "price" : 60.99,
    },
    {
        "id": 6,
        "image": "https://python-training-courses-74.webself.net/file/si1380186/Python-Certification-Training-Course-fi20934347x440.jpg",
        "title" : "Programming with python",
        "instructor": "Zaid Colt",
        "price" : 10.99,
    },
    {
        "id": 7,
        "image": "https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/105223655/original/e855caa504b0afff16a0d11215b0783ab9f2cbc2/send-you-the-complete-cyber-security-course-anonymous-browsing.jpg",
        "title" : "The Complete Cyber Security Course : Hackers Exposed!",
        "instructor": "Nathan david",
        "price" : 30.09,
    },
    {
        "id": 8,
        "image": "https://www.whizlabs.com/blog/wp-content/uploads/2018/04/aws-developer-associate-1.jpg",
        "title" : "AWS Certified Developer - Associate 2020",
        "instructor": "Rayan House",
        "price" : 20.99,
    },
    {
        "id": 9,
        "image": "https://www.simplilearn.com/ice9/free_resources_article_thumb/ML-banner_1.jpg",
        "title" : "Machine Learning A-Z™: Hands-On Python & R In Data Science",
        "instructor": "Team House",
        "price" : 10.99,
    },
    {
        "id": 10,
        "image": "https://www.simplilearn.com/ice9/free_resources_article_thumb/Course-Announcement-Angular-Self-Paced-Learning-Course.jpg",
        "title" : "Angular - The Complete Guide (2020 Edition)",
        "instructor": "Angela Colt",
        "price" : 6.99,
    }, {
        "id": 11,
        "image": "https://www.10bestdesign.com/blog/content/images/2018/03/26.jpg",
        "title" : "The Web Developer Bootcamp",
        "instructor": "Colt Steel",
        "price" : 11.99,
    },
    {
        "id": 12,
        "image": "https://miro.medium.com/max/1024/1*6l15igU_z2Uj15SzOGx1Iw.png",
        "title" : "The Data Science Course 2020: Complete Data Science",
        "instructor": "Jonas Jose",
        "price" : 16.99,
    },
    {
        "id": 13,
        "image": "https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/104580776/original/50bdc5fd8d913f4fa6053f48fcba22b3f8713bf7/sell-you-the-complete-javascript-guide-for-a-responsive-site.jpg",
        "title" : "The Complete JavaScript Course 2020: Build Real Projects!",
        "instructor": "David Portilia",
        "price" : 10.59,
    },
    {
        "id": 14,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSTqMi7mKHZZazqgKntkzGWJpMoriCGZzAn-w&usqp=CAU",
        "title" : "React - The Complete Guide (incl Hooks, React Router, Redux)",
        "instructor": "Rob Percivil",
        "price" : 11.99,
    },
    {
        "id": 15,
        "image": "https://cdn.lynda.com/course/2822348/2822348-637286285947413658-16x9.jpg",
        "title" : "Rest API Testing (Automation) from Scratch -RestAssured Java",
        "instructor": "David Kode",
        "price" : 12.99,
    },
    {
        "id": 16,
        "image": "https://www.amitysoft.com/img/course/Selenium-Training-in-Chennai.jpg",
        "title" : "Selenium WebDriver with Java -Basics to Advanced+Frameworks",
        "instructor": "Rahul Shetty",
        "price" : 19.99,

    }]
    export default course;